version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    #volumes:
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: hamann
      MYSQL_USER: hamann55
      MYSQL_PASSWORD: mypassword
      
    networks:
      - app-network


networks:
  app-network:
   driver: bridge

volumes:
  dbdata:
    driver: local

